id: mlops_train_forecast
namespace: projet705
tasks:
  - id: sarima_forecast
    type: io.kestra.plugin.scripts.shell.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    env: "{\"PG_HOST\":\"{{ kv('PG_HOST') }}\",\"PG_DB\":\"{{ kv('PG_DB') }}\",\"PG_USER\":\"{{ kv('PG_USER') }}\",\"PG_PASS\":\"{{ kv('PG_PASS') }}\",\"AWS_ACCESS_KEY_ID\":\"{{ kv('S3_ACCESS_KEY') }}\",\"AWS_SECRET_ACCESS_KEY\":\"{{ kv('S3_SECRET_KEY') }}\",\"AWS_DEFAULT_REGION\":\"{{ kv('S3_REGION') }}\",\"MODEL_REGISTRY_S3_BUCKET\":\"{{ kv('S3_BUCKET') }}\",\"MODEL_REGISTRY_S3_ENDPOINT_URL\":\"{{ kv('S3_ENDPOINT') }}\",\"MLFLOW_TRACKING_URI\":\"http://172.17.0.1:8050\",\"MLFLOW_REGISTERED_MODEL_NAME\":\"mlops_linky_sarima_705\"}"
    script: |
      cd /app/scripts_mlops
      python3 mlops_train_linky_705.py

  - id: notify_discord_success
    type: io.kestra.plugin.core.http.Request
    uri: "{{ kv('DISCORD_WEBHOOK_URL') }}"
    method: POST
    contentType: application/json
    body: |
      {
        "embeds": [{
          "title": "✅ Training Linky — Succès",
          "description": "Le training SARIMA `mlops_linky_training_3d` s'est terminé avec succès.",
          "color": 3066993,
          "fields": [
            { "name": "Namespace", "value": "projet705", "inline": true },
            { "name": "Exécution", "value": "{{ execution.id }}", "inline": true },
            { "name": "Démarré le", "value": "{{ execution.startDate }}", "inline": false }
          ]
        }]
      }

errors:
  - id: notify_discord_failure
    type: io.kestra.plugin.core.http.Request
    uri: "{{ kv('DISCORD_WEBHOOK_URL') }}"
    method: POST
    contentType: application/json
    body: |
      {
        "embeds": [{
          "title": "❌ Training Linky — Échec",
          "description": "Le training SARIMA `mlops_linky_training_3d` a échoué.",
          "color": 15158332,
          "fields": [
            { "name": "Namespace", "value": "projet705", "inline": true },
            { "name": "Exécution", "value": "{{ execution.id }}", "inline": true },
            { "name": "Erreur", "value": "{{ errorLogs() }}", "inline": false }
          ]
        }]
      }

triggers:
  - id: every_week
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 * * 0"
