id: mqtt_linky_gold
namespace: projet705
tasks:
  - id: dbt_gold
    type: io.kestra.plugin.scripts.shell.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    script: |
      cd /app/storage/main/projet705/_files/dbt
      dbt run --profiles-dir . --select linky_hourly 2>&1
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "5 * * * *"