services:
  kestra:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: kestra-dbt:latest
    pull_policy: never
    container_name: kestra
    restart: unless-stopped
    user: "root"
    command: server standalone
    ports:
      - "${KESTRA_PORT:-8082}:8080"
    volumes:
        - ./data:/app/storage
        - ./tmp:/tmp/kestra-wd
        - /var/run/docker.sock:/var/run/docker.sock
        - ${HOST_DBT_PATH}:/app/dbt
        - ${HOST_SCRIPTS_PATH}:/app/scripts
        - ${HOST_SQL_PATH}:/app/sql
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://${PG_HOST:-projet-db}:${PG_PORT:-5432}/${PG_DB:-airflow}?currentSchema=kestra
            driverClassName: org.postgresql.Driver
            username: ${PG_USER}
            password: ${PG_PASS}
        kestra:
          server:
            basic-auth:
              enabled: true
              username: ${KESTRA_ADMIN_USER}
              password: ${KESTRA_ADMIN_PASS}
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: /app/storage
          queue:
            type: postgres
          jdbc:
            cleaner:
              initial-delay: 1h
              fixed-delay: 1h
              retention: 2d
    extra_hosts:
      - "s3fast.lafrance.io:${S3_HOST_IP:-172.17.0.1}"
    networks:
      - projet-net
networks:
  projet-net:
    external: true
