replicaCount: 1

image:
  repository: saraelmountasser/fastapi-mlops
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  nodePort: 30088
  port: 8000

env:
  PG_HOST: "192.168.80.127"
  PG_DB: airflow
  PG_USER: airflow
  PG_PASS: airflow