name: deploy-prod

on:
  push:
    branches: [main]
    paths:
      - '10-flows/prod/**'
      - '140-sql/queries/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy flows to production
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy namespace files (SQL)
        uses: kestra-io/deploy-action@master
        with:
          namespace: projet713
          directory: ./140-sql
          resource: namespace_file
          server: http://localhost:30082
          user: ${{ secrets.KESTRA_ADMIN_USER }}
          password: ${{ secrets.KESTRA_ADMIN_PASS }}

      - name: Validate flows
        uses: kestra-io/validate-action@master
        with:
          directory: ./10-flows/prod
          resource: flow
          server: http://localhost:30082
          user: ${{ secrets.KESTRA_ADMIN_USER }}
          password: ${{ secrets.KESTRA_ADMIN_PASS }}

      - name: Deploy flows
        uses: kestra-io/deploy-action@master
        with:
          namespace: projet713
          directory: ./10-flows/prod
          resource: flow
          server: http://localhost:30082
          user: ${{ secrets.KESTRA_ADMIN_USER }}
          password: ${{ secrets.KESTRA_ADMIN_PASS }}
          delete: false
